-- CreateEnum
CREATE TYPE "ClaimCategory" AS ENUM ('SENSOR', 'PARCHE', 'TRANSMISOR', 'BASE_BOMBA', 'CABLE_TRANSMISOR', 'PDM');

-- CreateEnum
CREATE TYPE "ClaimErrorCode" AS ENUM ('SENSOR_FALLA', 'SENSOR_FALTA_ADHESIVO', 'SENSOR_DIFERENCIA_CAPILAR', 'SENSOR_PERDIDO', 'SENSOR_DESCONOCIDO', 'SENSOR_SANGRADO_COLOCACION', 'SENSOR_OTROS', 'PARCHE_FALTA_ADHESIVO', 'PARCHE_ERROR', 'PARCHE_OBSTRUCCION', 'PARCHE_BATERIA_AGOTADA', 'PARCHE_ERROR_CEBADO', 'PARCHE_DESACTIVADO', 'PARCHE_OTROS', 'TRANSMISOR_CONECTORES_OXIDADOS', 'TRANSMISOR_LUZ_VERDE_NO_PARPADEA', 'TRANSMISOR_PROBLEMAS_BATERIA', 'TRANSMISOR_ROTURA', 'TRANSMISOR_OTROS', 'BASE_BOMBA_CONECTORES_OXIDADOS', 'BASE_BOMBA_NO_ENCASTRA', 'BASE_BOMBA_NO_HACE_PITIDOS', 'BASE_BOMBA_ROTURA', 'BASE_BOMBA_OTROS', 'CABLE_NO_CARGA', 'CABLE_PIN_DOBLADO', 'CABLE_OTROS', 'PDM_NO_CARGA_NO_ENCIENDE', 'PDM_SE_APAGA_SOLO', 'PDM_NO_CARGA', 'PDM_ROTURA', 'PDM_OTROS');

-- AlterTable
ALTER TABLE "claims" ADD COLUMN     "claim_category" "ClaimCategory",
ADD COLUMN     "error_code" "ClaimErrorCode";
