-- Add new values to SupplyType enum
ALTER TYPE "SupplyType" ADD VALUE IF NOT EXISTS 'PARCHE_200U';
ALTER TYPE "SupplyType" ADD VALUE IF NOT EXISTS 'PARCHE_300U';
ALTER TYPE "SupplyType" ADD VALUE IF NOT EXISTS 'BASE_BOMBA_200U';
ALTER TYPE "SupplyType" ADD VALUE IF NOT EXISTS 'BASE_BOMBA_300U';

-- Add new values to ClaimCategory enum
ALTER TYPE "ClaimCategory" ADD VALUE IF NOT EXISTS 'PARCHE_200U';
ALTER TYPE "ClaimCategory" ADD VALUE IF NOT EXISTS 'PARCHE_300U';
ALTER TYPE "ClaimCategory" ADD VALUE IF NOT EXISTS 'BASE_BOMBA_200U';
ALTER TYPE "ClaimCategory" ADD VALUE IF NOT EXISTS 'BASE_BOMBA_300U';
